---
title: Douglas JD
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: xiajiandao@gmail.com
description: "“Start small”"
logo_location: https://placeholdit.imgix.net/~text?txtsize=30&bg=F8F8F8&txtclr=002E62&txt=LOGO&w=100&h=100
markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
exclude:
- README.md
excerpt_separator: "<!--more-->"
show_blog_header: true
